# #   _
#
#__            _ _     _
#  / _ \          (_) |   | |
# / /_\ \_ __  ___ _| |__ | | ___
# |  _  | '_ \/ __| | '_ \| |/ _ \
# | | | | | | \__ \ | |_) | |  __/
# \_| |_/_| |_|___/_|_.__/|_|\___|
#
#

#  Ansible playbook to setup cpu + memory sensu checks on client servers.
#  This script assumes sensu plugins are already installed on servers.

# Owner: Hammad Shah
# 2017
#

- name: Configure and start sensu cpu and memory checks on client servers
  hosts: localhost
  gather_facts: false
  serial: 1
  tasks:
    - name: Get hostname of remote server
      command: hostname
      register: server_name
    - name: add hostname argument to cpu script
      lineinfile:
        path: config/cpu_metrics.json
        regexp: 'command'
        line: '      "command": "metrics-cpu-pcnt-usage.rb --scheme PDNS.{{ server_name.stdout }}.cpu",'
      delegate_to: localhost
    - name: add hostname argument to memory script
      lineinfile:
        path: config/memory_metrics.json
        regexp: 'command'
        line: '      "command": "metrics-memory.rb --scheme PDNS.{{ server_name.stdout }}.mem",'
      delegate_to: localhost
    - name: copy cpu config to server
      copy:
        src:  config/cpu_metrics.json
        dest: /etc/sensu/conf.d/cpu_metrics.json
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"
      notify:
        - restart sensu-client service
    - name: copy memory config file to remote server
      copy:
        src:  config/memory_metrics.json
        dest: /etc/sensu/conf.d/memory_metrics.json
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"
      notify:
        - restart sensu-client service
  handlers:
    - name: restart sensu-client service
      service:
        name: sensu-client
        state: restarted
